version: 2
builds:
- id: kns
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  main: ./main.go
  binary: kns
archives:
- id: kns
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  formats: [ tar.gz ]
  files:
  - LICENSE
  wrap_in_directory: false
checksum:
  algorithm: sha256
  name_template: 'checksums_sha256.txt'
changelog:
  sort: asc
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source